#! /bin/sh
set -e

case "$1" in
    start)
        echo "loadling scull"
        #start-stop-daemon -S -n init -a /bin/scull_load
        start-stop-daemon -S -n scull
        ;;
    stop)
        echo "unloading scull"
        #start-stop-daemon -K -n scull_load
        #start-stop-daemon -K -n module_load
        #start-stop-daemon -S -n init -a /bin/scull_unload
        start-stop-daemon -K -n scull
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac
exit 0
